export const IPC_NOTIFICATION_EVENTS = {
  SUCCESS: 'NOTIFICATION_SUCCESS',
  FAILURE: 'NOTIFICATION_FAILURE',
  FATAL: 'NOTIFICATION_FATAL',
  ERROR: 'NOTIFICATION_ERROR',
  INFO: 'NOTIFICATION_INFO',
  VALIDATION: {
    ERROR: 'NOTIFICATION_VALIDATION_ERROR',
    SUCCESS: 'NOTIFICATION_VALIDATION_SUCCESS',
  },
} as const
